name: Build for Windows64
on: workflow_dispatch

jobs:
  build_windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.1'
      - name: Install and Build
        run: |
          sudo apt-get install libsdl2-2.0-0
          wget https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/amd64/libfaudio0_19.07-0~bionic_amd64.deb
          sudo dpkg -i libfaudio0_19.07-0~bionic_amd64.deb
          wget -nc https://dl.winehq.org/wine-builds/winehq.key
          sudo apt-key add winehq.key
          sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
          sudo apt update
          sudo apt install --install-recommends winehq-stable
          npm install
          npm run buildWindows
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: monkeytype-desktop-plugin-windows-build
          path: MonkeytypeDesktopPlugin-win32-x64
