name: Build for Windows64
on: workflow_dispatch

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.1'
      - name: Install and Build
        run: |
          sudo dpkg --add-architecture i386
          wget -nc https://dl.winehq.org/wine-builds/winehq.key
          sudo apt-key add winehq.key
          sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
          sudo apt update
          sudo apt install --install-recommends winehq-stable
          npm install
          npm run buildWindows
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: monkeytype-desktop-plugin-windows-build
          path: MonkeytypeDesktopPlugin-win32-x64
