name: Build for Windows64
on: workflow_dispatch

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Install and Build
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.1'
      - run: npm install
      - run: npm run buildWindows
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: monkeytype-desktop-plugin-windows-build
          path: MonkeytypeDesktopPlugin-win32-x64